baseURL = "https://grayzein.site/"
title = "GRAI"
languageCode = "id"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "GRAI"
  description = "Personal blog by Gray"
  author = "GRAI"
  images = ["/logo.svg"]
  
  defaultTheme = "light"
  disableThemeToggle = true
  
  ShowReadingTime = false
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  # [params.homeInfoParams]
    # Title = "GRAI"
    # Content = "Personal blog by Gray Zein Syah Putra"

  [params.profileMode]
    enabled = false

  # [[params.socialIcons]]
    # name = "email"
    # url = "mailto:gryzein@gmail.com"

[params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false

[params.label]
  icon = "/logo.svg"
  iconHeight = 35
  text = ""

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "cat-teknologi"
    name = "Teknologi"
    url = "https://grayzein.site/tags/teknologi/"
    weight = 20
  [[menu.main]]
    identifier = "cat-ai"
    name = "AI"
    url = "https://grayzein.site/tags/ai/"
    weight = 30
  [[menu.main]]
    identifier = "cat-blockchain"
    name = "Blockchain"
    url = "https://grayzein.site/tags/blockchain/"
    weight = 40
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
